{
    stakehouseAccounts(where: { numberOfDeposits_gt: "0" }) {
        accountId
        lastDepositDepositCount
        blsSigningKeyCipherText
        numberOfDeposits
        blsPubKeyDeposits {
            blsPubKey
            blsSignature
        }
    }
}
